version: '3'

services:
  pgsql:
    image: postgres:17.5
    container_name: pgsql
    ports:
      - "${PGSQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      TZ: ${TZ}
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - appandserver

networks:
  appandserver:

volumes:
  pgsql-data: